#event_index:
#    path:     /
#    defaults: { _controller: "YodaEventBundle:Event:index" }
#    methods:  GET

#event_show:
#    path:     /{id}/show
#    defaults: { _controller: "YodaEventBundle:Event:show" }
#    methods:  GET

#event_new:
#    path:     /new
#    defaults: { _controller: "YodaEventBundle:Event:new" }
#    methods:  [GET, POST]

#event_edit:
#    path:     /{id}/edit
#    defaults: { _controller: "YodaEventBundle:Event:edit" }
#    methods:  [GET, POST]

#event_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "YodaEventBundle:Event:delete" }
#   methods:  DELETE

event_attend:
  path: /{id}/attend.{format}
  defaults: {_controller: "YodaEventBundle:Event:attend",format: html}
  requirements:
    format: json

event_unattend:
  path: /{id}/unattend.{format}
  defaults: {_controller: "YodaEventBundle:Event:unattend", format: html}
  requirements:
    format: json

