# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~

    firewalls:
        secured_area:
            pattern: ^/
            form_login:
                check_path: _security_check
                login_path: /login
            logout:
                path: _demo_logout
                target: _demo
            anonymous: ~

    access_control:
        - { path: ^/event/new , roles: ROLE_USER }
        - { path: ^/event/create , roles: ROLE_USER }
