# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_EVENT_CREATE,ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: [ROLE_USER , ROLE_ADMIN,ROLE_ALLOWED_TO_SWITCH]

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        UserBundle\Entity\User: bcrypt


    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:            # Required
        our_database_users:
            entity: { class: UserBundle:User }

    firewalls:
        secured_area:
            pattern: ^/
            form_login:
                check_path: login_form
                login_path: login_form
            logout:
                path: logout
                target: event_index
            anonymous: ~
            switch_user: ~
            remember_me:
                key: "Order 1138"

    access_control:
        - { path: ^/login , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(_wdt|_profiler), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(css|js), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ , roles: ROLE_USER }

        #- { path: ^/event/delete, roles : ROLE_ADMIN }
