services:
#    yoda_event.example:
#        class: YodaEventBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
  tyoda_event.twig.event_extension:
    class: YodaEventBundle\Twig\EventExtension
    arguments: []
    tags:
      - { name: twig.extension}

  doctrine.event_listener:
    class: YodaEventBundle\Doctrine\EventListener
    arguments: []
    tags:
      - { name: doctrine.event_listener, event: prePersist}