<?php

namespace YodaEventBundle\Repository;
use Symfony\Component\HttpFoundation\Response;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{

    public function upcomingEvents($max = null)
    {
        $qb = $this->createQueryBuilder('e')
            ->addOrderBy('e.time','ASC')
            ->andWhere('e.time > :now')
            ->setParameter('now', new \DateTime());

        if($max) $qb->setMaxResults($max);

        return $qb->getQuery()->execute();
    }

    public function getRecentlyUpdatedEvent(){

        $events =  $this->createQueryBuilder('e')
        ->andWhere('e.updatedAt > :since')
        ->setParameter('since',new \DateTime('24 hours ago'))
        ->getQuery()
        ->execute();

        return $events;
    }
}
